<?php

namespace AppBundle\Repository;

/**
 * UserLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
